name: "OverCloudAirways Build"

on: [pull_request]

env:
 NETCORE_VERSION: '7.0.x'

jobs:
  setup:
      name: Choose Secrets Environment Job
      runs-on: windows-latest
      steps:
        - id: setup
          name: Setup Environment Setp
          run: |
            $envSelector = "${{ github.event.inputs.environmentselector }}"
            Write-Host "Environment Selector: $envSelector Branch ${{ github.ref }}"
            if ($envSelector -eq '' -or $envSelector -eq 'default') {            
              if ('${{ github.ref }}' -eq 'refs/heads/main') { 
                echo "::set-output name=build_env::PROD_"
              } else {
                echo "::set-output name=build_env::DEV_"
              }
            } else {
              echo "::set-output name=build_env::$envSelector"
            }
      outputs:
        build_env: ${{ steps.setup.outputs.build_env }}
        
 build:
  name: Build
  needs: setup
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v2
    - uses: southpolesteve/cosmos-emulator-github-action@v1
    - name: Setup .NET SDK 7.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
  
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: ${{ env.NETCORE_VERSION }}
     
    - run: npm install -g azurite
    - shell: bash
      run: azurite-table &

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal
